name: Develop CI/CD Pipeline

on:
  push:
    branches:
      - develop

jobs:
  deploy:
    name: Deploy to Develop
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Teste
        run: echo env.TEST

      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     workflow: testBuild.yml
      #     workflow_conclusion: success

      - name: Checkout
        uses: actions/checkout@v3
