name: Test Docker

on:
  push:
    branches:
      - 'main'

# env:
#   URL_MOCKED: http://localhost:3000
#   IMAGE_TEST: test-nx

jobs:
  build:
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Login on Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Check cache
        id: check-cache
        uses: actions/cache@v3
        with:
          key: ${{ runner.os }}-yarn-${{ hashFiles('**/yarn.lock') }}
          node-version: 16
          path: |
            **/node_modules
            **/.eslintcache
          restore-keys: ${{ runner.os}}-yarn-

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and push
        uses: docker/build-push-action@v4
        with:
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline:latest
