jobs:

  build:
    environment:
      name: gitActionsTest
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx on Linux
        uses: docker/setup-buildx-action@v2

      # - name: Login on Docker Hub
      #   uses: docker/login-action@v2
      #   with:
      #     password: ${{ secrets.DOCKERHUB_TOKEN }}
      #     username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: nextjs/yarn.lock
          node-version: '16'

      - name: Set up App
        run: |
          cd ./nextjs
          yarn install --frozen-lockfile

      - name: Build Offical Image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline:latest
          target: builder

name: Pipeline Test
on: pull_request
