jobs:
  deploy:
    environment:
      name: gitActionsTest.develop
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: testBuild.yml
          workflow_conclusion: success

      - name: Teste
        run: echo env.TEST

      # - name: Download artifact
      #   uses: dawidd6/action-download-artifact@v2
      #   with:
      #     workflow: testBuild.yml
      #     workflow_conclusion: success

      - name: Checkout
        uses: actions/checkout@v3

name: Develop
on:
  push:
    branches:
      - develop
