jobs:
  build:
    continue-on-error: ${{ matrix.experimental }}
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    # runs-on: ${{ matrix.os }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      # - if: ${{ matrix.os == 'windows-2019' }}
      #   name: Set up Docker Buildx on Windows
      #   uses: docker/setup-buildx-action@v2
      #   with:
      #     driver: docker

      # - if: ${{ matrix.os == 'macos-11' }}
      #   name: Setup Docker Driver on Mac
      #   uses: douglascamata/setup-docker-macos-action@v1-alpha

      # - if: ${{ matrix.os == 'macos-11' }}
      #   name: Set up Docker Buildx on Mac
      #   uses: docker/setup-buildx-action@v2

      - name: Set up Docker Buildx on Linux
        uses: docker/setup-buildx-action@v2

      - name: Login on Docker Hub
        uses: docker/login-action@v2
        with:
          password: ${{ secrets.DOCKERHUB_TOKEN }}
          username: ${{ secrets.DOCKERHUB_USERNAME }}

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: teste/yarn.lock
          node-version: '16'

      - name: Set up App
        run: |
          cd ./teste
          yarn install --frozen-lockfile

      - name: Build Offical Image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline:latest
          target: builder
    strategy:
      matrix:
        achitecture:
          - x64
        experimental: [true]
        # os: [ubuntu-latest, macos-11, windows-2019]

name: Pipeline Test
on:
  push:
    branches: ['master']
