name: Test Main CI/CD Pause Pipeline

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Aproval for deployment
        uses: trstringer/manual-approval@v1
        with:
          secret: ${{ github.TOKEN }}
          approvers: jvsm123
          minimum-approvals: 2
          issue-title: 'Deploying PROD release'
          issue-body: 'Please approve or deny the deployment'
          exclude-workflow-initiator-as-approver: true
          additional-approved-words: 'aproved'
          additional-denied-words: 'denied'

      - name: Run test echo
        run: echo "Test echo"
