jobs:
  deploy:
    environment:
      name: gitActionsTest
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Download artifact
        uses: dawidd6/action-download-artifact@v2
        with:
          workflow: testBuild.yml
          workflow_conclusion: success

      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx on Linux
        uses: docker/setup-buildx-action@v2

name: Master
on:
  push:
    branches:
      - 'master'
  workflow_run:
    types:
      - completed
    workflows:
      - Develop
