name: Staging Test Workflow

on:
  workflow_run:
    types:
      - requested
    workflows:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      id-token: write
      packages: write

    steps:
      - name: Test
        run: echo Test
