jobs:
  build:
    environment:
      name: gitActionsTest.test
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx on Linux
        uses: docker/setup-buildx-action@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: nextjs/yarn.lock
          node-version: '16'

      - name: Set up App
        run: |
          cd nextjs
          yarn install --frozen-lockfile

      - name: Build
        run: |
          cd nextjs
          yarn run nx build teste

      - name: Upload build files
        uses: actions/cache@v3
        with:
          key: test-${{ github.sha }}
          path: nextjs/dist

name: Test
on: 
  pull_request:
    branches:
      - "*"
      - "!master"
      - "!develop"
  push:
    branches:
      - "*"
      - "!master"
      - "!develop"
