env:
  TEST: ${{ github.sha }}

jobs:
  build:
    environment:
      name: gitActionsTest.test
    name: ubuntu-latest_Pipeline
    permissions:
      contents: read
      id-token: write
      packages: write
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3

      - name: Set up Docker Buildx on Linux
        uses: docker/setup-buildx-action@v2

      - name: Set up Node
        uses: actions/setup-node@v3
        with:
          cache: 'yarn'
          cache-dependency-path: nextjs/yarn.lock
          node-version: '16'

      - name: Set up App
        run: |
          cd nextjs
          yarn install --frozen-lockfile

      - name: Test
        run: |
          cd nextjs
          yarn run nx build teste

      - name: Build Offical Image
        uses: docker/build-push-action@v4
        with:
          cache-from: type=gha
          cache-to: type=gha,mode=max
          context: .
          file: ./Dockerfile
          push: false
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/pipeline:latest
          target: builder

      - name: Upload dist files
        uses: actions/upload-artifact@v3
        with:
          name: test-dist-${{ github.sha }}
          path: nextjs/dist
          retention-days: 1

name: Test
on: 
  pull_request:
    branches:
      - "*"
      - "!master"
      - "!develop"
  push:
    branches:
      - "*"
      - "!master"
      - "!develop"
